# draw_bold_text_with_brigth_colors = true

# [theme]
# theme = "Google.dark"

[colors]
# author = "Chris Kempson"
# name = "Google (dark)"

[colors.bright]
black = "#969896"
blue = "#3971ed"
cyan = "#3971ed"
green = "#198844"
magenta = "#a36ac7"
red = "#cc342b"
white = "#ffffff"
yellow = "#fba922"

[colors.cursor]
cursor = "#c5c8c6"
text = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#3971ed"
cyan = "#3971ed"
green = "#198844"
magenta = "#a36ac7"
red = "#cc342b"
white = "#c5c8c6"
yellow = "#fba922"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
