// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1679485351);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1679485711);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1679485591);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1679485471);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1679485381);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{f3e1a719-4f50-4d73-96d8-0d77f73a46a9}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1679485321);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{15df854c-5133-4cc4-9f3a-625a997cf598}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1679485322");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230314223709");
user_pref("browser.startup.homepage_override.mstone", "111.0");
user_pref("browser.startup.lastColdStartupCheck", 1679485322);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1679485322246");
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "111.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230314223709");
user_pref("extensions.lastAppVersion", "111.0");
user_pref("extensions.lastPlatformVersion", "111.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"be0db984-ae20-43bf-91a6-7de7c1b832d5\",\"pictureinpicture@mozilla.org\":\"bd47bc93-32bd-4106-b47c-187add3d9dd0\",\"screenshots@mozilla.org\":\"32f8691c-da56-427d-83fe-f78692dfe593\",\"webcompat-reporter@mozilla.org\":\"0d1e22ee-9286-4338-9be2-23c35b38ed54\",\"webcompat@mozilla.org\":\"8c3e96fd-94d0-424d-a81f-210a5a75caad\",\"default-theme@mozilla.org\":\"d50b948a-a98d-4507-abcb-b5a0d1bc1c9d\",\"addons-search-detection@mozilla.com\":\"57a60cdc-a33e-4057-bc87-c677cc58b96f\",\"google@search.mozilla.org\":\"dbf34391-e2d1-4603-b7e0-4c2616ac345b\",\"amazondotcom@search.mozilla.org\":\"8f437e83-8c2b-4fc8-aeb2-8e5280c5bd5c\",\"wikipedia@search.mozilla.org\":\"e19a6a06-5a93-473e-a51f-9d82b11ec0fd\",\"bing@search.mozilla.org\":\"0ec5a067-7c8f-4ea0-8e98-4f1161353e6d\",\"ddg@search.mozilla.org\":\"ef12abab-fae6-482c-b3fb-79b7759df855\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastDownload", 1679485389);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1679485387);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1679485389);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20230314223709");
user_pref("media.gmp-manager.lastCheck", 1679485387);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "b51a0d09-b9fb-4bbe-8fc6-aac55a0cf78e");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1679485320);
user_pref("toolkit.telemetry.cachedClientID", "de07e9c3-ccc0-4ea7-bbf0-b00a2d550f53");
user_pref("toolkit.telemetry.previousBuildID", "20230314223709");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
